# Generated by Django 3.2.4 on 2021-07-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_driver_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='area',
        ),
    ]
